1 html Первое домашнее задание
pb56/purple-home_work pull request #2
Opened 2024-04-29 16:49 UTC by pb56

2024-04-30 03:12 UTC, GitEsense requested changes
Отправляю на некоторые исправления, в целом всё отлично, поправите - сдавайте на повторную проверку на платформе, достаточно будет указать комментарий "внесены правки", если ссылка на ПР не изменится

2024-04-30 03:12 UTC, GitEsense commented on 1-blog/index.html
> +            <a href="#">Мой блог</a>
Вот это хорошо бы объединить в одну ссылку и вынести за навигационное меню, т.к. это всё-таки "логотип" и он же ссылка

2024-04-30 03:12 UTC, GitEsense commented on 1-blog/index.html
> +        <input type="search" name="" id="#">
name хорошо бы указывать, ведь именно этот атрибут упадёт в форму, в такой записи оно подразумевает "отлавливать событие", но ок, нам важно будет стилизовать, а не функционал, но надо иметь ввиду

2024-04-30 03:12 UTC, GitEsense commented on 1-blog/index.html
> +        <span>FRONTEND • 12 мая 2024</span>
Вот это лучше сделать блочным тегом "параграф", всё-таки дальше у нас идёт с новой строки

2024-04-30 03:12 UTC, GitEsense commented on 1-blog/index.html
> +        </div>
Не нужно оборачивать заголовок в div - он сам имеет блочное поведение, так же неверно начинать "заголовок" со второго - это нарушение иерархии, сначала всегда идёт h1 и лишь потом заголовки по семантике идут h2-6 (вот их уже может быть несколько)

2024-04-30 03:12 UTC, GitEsense commented on 1-blog/index.html
> +            <p>Разработчик</p>
А вот тут рекомендовал бы обернуть в div (блочный элемент, объединяющий контент) и тогда "имя" и "профессия" - будут текстовыми блоками "параграф"

2024-04-30 03:12 UTC, GitEsense commented on 1-blog/index.html
> +    </section>
Картинку так же можно не выделять в отдельную секцию, но обёртка для изображений вещь полезная - можно оставить, так же можете почитать отдельно про другие семантические теги (picture например, но не для применения, а понимания какие ещё есть)

2024-04-30 03:12 UTC, GitEsense commented on 1-blog/index.html
> +        <h4>Универсального ответа на вопрос, как тот или иной цвет влияет на разных людей, нет. Эмоциональная и поведенческая реакция каждого человека зависит от личного опыта. Вместе с тем можно выд
Вместо заголовков тут лучше воспользоваться параграфами, ведь это идёт "текст", а не "заголовок"

2024-04-30 03:12 UTC, GitEsense commented on 2-form/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
В занятиях особо не уделялось внимание, но ознакомьтесь дополнительно с метатегами и укажите например авторство и описание

2024-04-30 03:12 UTC, GitEsense commented on 2-form/index.html
> +      </div>
Это является частью формы - считаем, что "шапка", поэтому лучше вложить в форму

2024-04-30 03:12 UTC, GitEsense commented on 2-form/index.html
> +        <textarea name="mycompany" id="mycompany" cols="20" rows="1">Moя компания</textarea required>
Это такой же текстовый инпут, как и Имя \ фамилия, хорошо бы исправить.
На макете этот инпут отличается, потому что показывает состояние "заполнен" и "фокус", более подробно будет разбор при изучении стилей

2024-04-30 14:58 UTC, pb56 commented on 2-form/index.html
> +      </div>
Понял

2024-04-30 14:58 UTC, pb56 commented on 2-form/index.html
> +        <textarea name="mycompany" id="mycompany" cols="20" rows="1">Moя компания</textarea required>
Состояние "заполнен" и "фокус" и ввело меня в заблуждение, исправлю.

2024-04-30 15:48 UTC, pb56 commented on 1-blog/index.html
> +            <p>Разработчик</p>
Так этот блок у меня уже обёрнут в div, поменяю только span на параграф

2024-04-30 15:50 UTC, pb56 commented on 1-blog/index.html
> +        </div>
Тонкий момент, отметил себе

2024-04-30 15:53 UTC, pb56 commented on 1-blog/index.html
> +        <input type="search" name="" id="#">
На самом деле name здесь я тупо прозевал, отмечу у себя. Спасибо.

2024-04-30 15:56 UTC, GitEsense commented on 1-blog/index.html
> +            <p>Разработчик</p>
> Так этот блок у меня уже обёрнут в div, поменяю только span на параграф

Как раз и получается 
```html
<div>
   <img>
   <div>
      <p>
      <p>
   </div>
</div>
```

2024-05-01 10:12 UTC, GitEsense approved these changes
В целом всё ок, но внимательнее к деталям, так же комментарии, которые остаются - имеют отношение не к конкретной строке, а в целом

2024-05-01 10:12 UTC, GitEsense commented on 1-blog/index.html
> +        <a href="#">B Мой блог</a>
Всё-таки лучше вынести за nav (поставить перед ним)

2024-05-01 10:12 UTC, GitEsense commented on 1-blog/index.html
> +      <div>
И всё-таки не нужно h1 в данном случае заворачивать в div

2024-05-01 16:16 UTC, pb56 commented on 1-blog/index.html
> +        <a href="#">B Мой блог</a>
Недоглядел, исправил.

2024-05-01 16:16 UTC, pb56 commented on 1-blog/index.html
> +      <div>
Исправил

2024-05-01 16:21 UTC, merged